apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: your-flask-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: POSTGRES_DB
            # Repeat for other environment variables
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  DB_NAME=postgres
  DB_USER=postgres.ppoohvwxcftgaqioemzy
  DB_PASSWORD=ufnvauifaj1_
  DB_HOST=aws-0-eu-central-1.pooler.supabase.com
  DB_PORT=5432

