name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Vercel
        run: |
          vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          DB_NAME: ${{ secrets.postgres }}
          DB_USER: ${{ secrets.postgres.ppoohvwxcftgaqioemzy }}
          DB_PASSWORD: ${{ secrets.ufnvauifaj1_ }}
          DB_HOST: ${{ secrets.aws-0-eu-central-1.pooler.supabase.com }}
          DB_PORT: ${{ secrets.5432 }}
